### ISSUE TITLE
Webscraping comma in the player name

### ISSUE THREAD

**Issue by tonper19** [tonper19/ballgame#3]
#### Webscraping logical error

When the player name contains a comma it is separated into an additional field. The surname contains the bold string, and the first name becomes two fields. When the ETL process reads the csv file, the field Team (third column) contains the part of the first name after the comma, the AB field contains a null string causing the ETL to abend. 

Example: Italy Serie A 2023 batting: PAULA José-Andres, Gregorio
 
The process should replace commas in any string field by spaces to avoid separation into additional fields in the csv file.

**Comment by enavarrocu** [comment]
Can you please provide the url?

**Comment by tonper19** [comment]
https://www.fibs.it/en/events/2023-serie-a-baseball/stats/general/all/batting

Player: PAULA José-Andres, Gregorio

**Comment by tonper19** [comment]
https://www.fibs.it/en/events/2022-fibs-serie-a-baseball-maschile/stats/general/all/pitching

HABECK Marc-André, René
